spring:
  profiles: dev

eureka:
  client:
    register-with-eureka: true     # 注册到eureka服务
    fetch-registry: true # 定期从服务端获取服务注册并信息以供使用
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka    # 指定了Eureka客户端应该连接到哪个Eureka服务器来获取服务注册表信息
  instance:
    instance-id: ${spring.application.name}${server.port}

provider:
  service:
    url: http://provider-payment-service/